import base64
import hashlib
import os

from cryptography.fernet import Fernet, InvalidToken

_key: Fernet | None = None


def _get_fernet() -> Fernet:
    global _key
    if _key is not None:
        return _key

    raw = os.environ.get("SGFLEET_ENCRYPTION_KEY", "")
    if not raw:
        raise RuntimeError(
            "SGFLEET_ENCRYPTION_KEY environment variable is not set. "
            "It should be generated by init.sh and stored in .env."
        )

    # Hex string -> SHA-256 -> URL-safe base64 (32 bytes) -> Fernet key
    digest = hashlib.sha256(bytes.fromhex(raw)).digest()
    key_bytes = base64.urlsafe_b64encode(digest)
    _key = Fernet(key_bytes)
    return _key


def encrypt(plaintext: str) -> str:
    """Encrypt a string and return a base64-encoded ciphertext."""
    if not plaintext:
        return ""
    return _get_fernet().encrypt(plaintext.encode("utf-8")).decode("utf-8")


def decrypt(ciphertext: str) -> str:
    """Decrypt a base64-encoded ciphertext and return the plaintext."""
    if not ciphertext:
        return ""
    try:
        return _get_fernet().decrypt(ciphertext.encode("utf-8")).decode("utf-8")
    except InvalidToken as exc:
        raise RuntimeError(f"Decryption failed — SGFLEET_ENCRYPTION_KEY may have changed: {exc}") from exc
