export interface SglangFlag {
  name: string;
  description: string;
  type: "bool" | "int" | "float" | "string" | "enum";
  defaultValue?: string;
  options?: string[];
  category: string;
}

export const CONTEXT_LENGTH_PRESETS = [
  { label: "8K", value: 8192 },
  { label: "16K", value: 16384 },
  { label: "32K", value: 32768 },
  { label: "48K", value: 49152 },
  { label: "64K", value: 65536 },
  { label: "128K", value: 131072 },
  { label: "192K", value: 196608 },
  { label: "256K", value: 262144 },
];

export const MAX_OUTPUT_LENGTH_PRESETS = [
  { label: "256", value: 256 },
  { label: "512", value: 512 },
  { label: "1K", value: 1024 },
  { label: "2K", value: 2048 },
  { label: "4K", value: 4096 },
  { label: "8K", value: 8192 },
  { label: "16K", value: 16384 },
  { label: "32K", value: 32768 },
  { label: "Unlimited", value: -1 },
];

export const SGLANG_FLAGS: SglangFlag[] = [
  // Memory and scheduling
  {
    name: "--mem-fraction-static",
    description:
      "Fraction of GPU memory for static allocation (model weights + KV cache pool). Reduce if you see OOM errors. Auto-computed from GPU memory when unset.",
    type: "float",
    category: "Memory",
  },
  {
    name: "--max-running-requests",
    description: "Maximum number of concurrent running requests",
    type: "int",
    category: "Memory",
  },
  {
    name: "--max-queued-requests",
    description: "Maximum number of queued requests. Ignored in disaggregation mode.",
    type: "int",
    category: "Memory",
  },
  {
    name: "--max-total-tokens",
    description:
      "Maximum tokens in the memory pool. Auto-calculated from memory fraction when unset. Typically used for development and debugging.",
    type: "int",
    category: "Memory",
  },
  {
    name: "--chunked-prefill-size",
    description:
      "Max tokens per chunk for chunked prefill. Reducing this helps avoid OOM on long prompts. Set to -1 to disable.",
    type: "int",
    category: "Memory",
  },
  {
    name: "--max-prefill-tokens",
    description: "Max tokens in a prefill batch. Real bound is the max of this value and the model context length.",
    type: "int",
    defaultValue: "16384",
    category: "Memory",
  },
  {
    name: "--prefill-max-requests",
    description: "Max requests in a prefill batch. No limit when unset.",
    type: "int",
    category: "Memory",
  },
  {
    name: "--page-size",
    description: "Number of tokens in a paged attention page",
    type: "int",
    defaultValue: "1",
    category: "Memory",
  },
  {
    name: "--disable-radix-cache",
    description: "Disable radix tree-based KV cache reuse between requests",
    type: "bool",
    category: "Memory",
  },
  {
    name: "--disable-overlap-schedule",
    description: "Disable overlap scheduling between prefill and decode",
    type: "bool",
    category: "Memory",
  },
  {
    name: "--disable-decode-cuda-graph",
    description: "Disable CUDA graph capture for the decode phase",
    type: "bool",
    category: "Memory",
  },
  {
    name: "--disable-prefill-cuda-graph",
    description: "Disable CUDA graph capture for the prefill phase",
    type: "bool",
    category: "Memory",
  },
  {
    name: "--radix-eviction-policy",
    description: "Radix tree eviction policy for KV cache reuse",
    type: "enum",
    defaultValue: "lru",
    options: ["lru", "lfu", "slru", "priority"],
    category: "Memory",
  },
  {
    name: "--schedule-policy",
    description: "Request scheduling policy. LPM maximizes prefix match, FCFS is first-come-first-served.",
    type: "enum",
    defaultValue: "fcfs",
    options: ["lpm", "random", "fcfs", "dfs-weight", "lof", "priority", "routing-key"],
    category: "Memory",
  },
  {
    name: "--schedule-conservativeness",
    description:
      "Scheduler conservativeness (larger = more conservative). Increase if you see requests being retried frequently.",
    type: "float",
    defaultValue: "1.0",
    category: "Memory",
  },
  {
    name: "--enable-priority-scheduling",
    description: "Enable priority scheduling. Higher priority integer values are scheduled first by default.",
    type: "bool",
    category: "Memory",
  },
  {
    name: "--default-priority-value",
    description: "Default priority for requests that do not specify an explicit priority",
    type: "int",
    category: "Memory",
  },
  {
    name: "--enable-dynamic-chunking",
    description:
      "Dynamically adjust chunk sizes for pipeline parallelism to maintain consistent execution time across chunks.",
    type: "bool",
    category: "Memory",
  },

  // Model and tokenizer
  {
    name: "--context-length",
    description: "Override the model's maximum context length. When unset, uses the value from config.json.",
    type: "int",
    category: "Model",
  },
  {
    name: "--dtype",
    description:
      "Data type for model weights and activations. Auto uses FP16 for FP32/FP16 models and BF16 for BF16 models.",
    type: "enum",
    defaultValue: "auto",
    options: ["auto", "half", "float16", "bfloat16", "float", "float32"],
    category: "Model",
  },
  {
    name: "--quantization",
    description: "Weight quantization method for the model",
    type: "enum",
    options: [
      "awq",
      "fp8",
      "mxfp8",
      "gptq",
      "marlin",
      "gptq_marlin",
      "awq_marlin",
      "bitsandbytes",
      "gguf",
      "modelopt",
      "modelopt_fp8",
      "modelopt_fp4",
      "auto-round",
      "compressed-tensors",
      "unquant",
    ],
    category: "Model",
  },
  {
    name: "--kv-cache-dtype",
    description: 'Data type for KV cache storage. "auto" uses model data type. FP8 options available for CUDA 11.8+.',
    type: "enum",
    defaultValue: "auto",
    options: ["auto", "fp8_e5m2", "fp8_e4m3", "bf16", "bfloat16", "nvfp4", "fp4_mx_block16"],
    category: "Model",
  },
  {
    name: "--load-format",
    description: "Format of model weights to load. Auto tries safetensors first, falls back to pytorch bin.",
    type: "enum",
    defaultValue: "auto",
    options: [
      "auto",
      "pt",
      "safetensors",
      "npcache",
      "dummy",
      "gguf",
      "bitsandbytes",
      "layered",
      "flash_rl",
      "fastsafetensors",
      "runai_streamer",
    ],
    category: "Model",
  },
  {
    name: "--quantization-param-path",
    description: "Path to JSON file with KV cache scaling factors. Should be supplied when KV cache dtype is FP8.",
    type: "string",
    category: "Model",
  },
  {
    name: "--trust-remote-code",
    description: "Allow custom models from the HuggingFace Hub to execute their own modeling files",
    type: "bool",
    category: "Model",
  },
  {
    name: "--revision",
    description: "Specific model version: branch name, tag, or commit ID",
    type: "string",
    category: "Model",
  },
  {
    name: "--tokenizer-mode",
    description: "'auto' uses the fast tokenizer if available; 'slow' always uses the slow tokenizer.",
    type: "enum",
    defaultValue: "auto",
    options: ["auto", "slow"],
    category: "Model",
  },
  {
    name: "--tokenizer-backend",
    description:
      "Tokenizer library: huggingface (default) or fastokens for faster tokenization (requires fastokens package).",
    type: "enum",
    defaultValue: "huggingface",
    options: ["huggingface", "fastokens"],
    category: "Model",
  },
  {
    name: "--tokenizer-path",
    description: "Path to a separate tokenizer, distinct from the model path",
    type: "string",
    category: "Model",
  },
  {
    name: "--tokenizer-worker-num",
    description: "Number of tokenizer manager worker processes",
    type: "int",
    defaultValue: "1",
    category: "Model",
  },
  {
    name: "--detokenizer-worker-num",
    description: "Number of detokenizer manager worker processes",
    type: "int",
    defaultValue: "1",
    category: "Model",
  },
  {
    name: "--chat-template",
    description: "Builtin chat template name or path to a custom chat template file",
    type: "string",
    category: "Model",
  },
  {
    name: "--hf-chat-template-name",
    description: 'When the tokenizer has multiple named chat templates, select which one to use (e.g., "tool_use").',
    type: "string",
    category: "Model",
  },
  {
    name: "--is-embedding",
    description: "Use the CausalLM as an embedding model instead of a generative model",
    type: "bool",
    category: "Model",
  },
  {
    name: "--enable-multimodal",
    description: "Enable multimodal functionality. No effect if the model is not multimodal.",
    type: "bool",
    category: "Model",
  },
  {
    name: "--model-impl",
    description:
      'Which model implementation: "auto" tries SGLang first then Transformers, "sglang" forces SGLang, "transformers" forces HuggingFace.',
    type: "enum",
    defaultValue: "auto",
    options: ["auto", "sglang", "transformers"],
    category: "Model",
  },
  {
    name: "--reasoning-parser",
    description: "Parser for reasoning/thinking models to structure thinking-output separation",
    type: "enum",
    options: ["deepseek-r1", "deepseek-v3", "glm45", "gpt-oss", "kimi", "qwen3", "qwen3-thinking", "step3"],
    category: "Model",
  },
  {
    name: "--strip-thinking-cache",
    description: "Skip caching reasoning-model output in the radix tree on request finish",
    type: "bool",
    category: "Model",
  },
  {
    name: "--enable-strict-thinking",
    description: "Enable strict token filtering during the thinking phase of reasoning models",
    type: "bool",
    category: "Model",
  },

  // Parallelism
  {
    name: "--tensor-parallel-size",
    description: "Tensor parallelism size (TP). Splits model weights across this many GPUs.",
    type: "int",
    defaultValue: "1",
    category: "Parallelism",
  },
  {
    name: "--pipeline-parallel-size",
    description: "Pipeline parallelism size (PP). Splits model layers across stages on different GPUs.",
    type: "int",
    defaultValue: "1",
    category: "Parallelism",
  },
  {
    name: "--data-parallel-size",
    description: "Data parallelism size (DP). Replicates the full model across this many GPU sets for throughput.",
    type: "int",
    defaultValue: "1",
    category: "Parallelism",
  },
  {
    name: "--num-expert-parallel-size",
    description: "Expert parallel size for MoE models. Distributes experts across GPUs.",
    type: "int",
    defaultValue: "1",
    category: "Parallelism",
  },
  {
    name: "--attention-context-parallel-size",
    description: "Attention context parallelism size. Splits attention computation across GPUs.",
    type: "int",
    category: "Parallelism",
  },
  {
    name: "--expert-parallel-size",
    description: "Expert parallel size (EP) for MoE models",
    type: "int",
    category: "Parallelism",
  },
  {
    name: "--pp-max-micro-batch-size",
    description: "Max micro batch size for pipeline parallel stages",
    type: "int",
    category: "Parallelism",
  },
  {
    name: "--pp-async-batch-depth",
    description: "Async batch depth for pipeline parallelism. 0 disables.",
    type: "int",
    defaultValue: "0",
    category: "Parallelism",
  },

  // Serving
  {
    name: "--host",
    description: "HTTP server bind address",
    type: "string",
    defaultValue: "0.0.0.0",
    category: "Serving",
  },
  { name: "--port", description: "HTTP server port", type: "int", defaultValue: "30000", category: "Serving" },
  {
    name: "--stream-interval",
    description: "Interval (token length) for streaming output chunks",
    type: "int",
    defaultValue: "1",
    category: "Serving",
  },
  {
    name: "--stream-output",
    description: "Stream output by default [Deprecated: use --incremental-streaming-output]",
    type: "bool",
    category: "Serving",
  },
  {
    name: "--incremental-streaming-output",
    description: "Output as a sequence of disjoint segments instead of cumulative output",
    type: "bool",
    category: "Serving",
  },
  {
    name: "--skip-server-warmup",
    description: "Skip the server warmup phase on startup",
    type: "bool",
    category: "Serving",
  },
  {
    name: "--served-model-name",
    description: "Override the model name returned by the /v1/models endpoint",
    type: "string",
    category: "Serving",
  },
  {
    name: "--weight-version",
    description: "Version identifier for the loaded model weights",
    type: "string",
    defaultValue: "default",
    category: "Serving",
  },
  { name: "--enable-metrics", description: "Enable Prometheus metrics endpoint", type: "bool", category: "Serving" },
  {
    name: "--enable-mfu-metrics",
    description: "Enable estimated MFU (Model FLOPs Utilization) Prometheus metrics",
    type: "bool",
    category: "Serving",
  },
  { name: "--enable-trace", description: "Enable OpenTelemetry tracing", type: "bool", category: "Serving" },
  {
    name: "--enable-cache-report",
    description: "Return number of cached tokens in usage.prompt_tokens_details",
    type: "bool",
    category: "Serving",
  },
  {
    name: "--log-requests",
    description: "Log metadata, inputs, and outputs of all requests",
    type: "bool",
    category: "Serving",
  },
  {
    name: "--log-level-request",
    description: "Log level for requests",
    type: "enum",
    defaultValue: "warning",
    options: ["debug", "info", "warning", "error", "critical"],
    category: "Serving",
  },
  {
    name: "--log-level",
    description: "Logging level for all loggers",
    type: "enum",
    defaultValue: "info",
    options: ["debug", "info", "warning", "error", "critical"],
    category: "Serving",
  },
  {
    name: "--log-level-http",
    description: "Logging level for the HTTP server. Falls back to --log-level when unset.",
    type: "string",
    category: "Serving",
  },
  {
    name: "--log-requests-level",
    description: "Request log detail: 0=metadata, 1=+sampling params, 2=+partial I/O, 3=full I/O",
    type: "enum",
    defaultValue: "2",
    options: ["0", "1", "2", "3"],
    category: "Serving",
  },
  {
    name: "--log-requests-format",
    description: "Request log format: human-readable text or structured JSON",
    type: "enum",
    defaultValue: "text",
    options: ["text", "json"],
    category: "Serving",
  },
  {
    name: "--log-requests-target",
    description: "Log requests to stdout and/or a directory path",
    type: "string",
    category: "Serving",
  },
  {
    name: "--show-time-cost",
    description: "Show time cost of custom marks in logs",
    type: "bool",
    category: "Serving",
  },
  {
    name: "--api-key",
    description: "API key for authentication (used in OpenAI-compatible endpoints)",
    type: "string",
    category: "Serving",
  },
  {
    name: "--admin-api-key",
    description: "Admin API key for administrative/control endpoints",
    type: "string",
    category: "Serving",
  },
  { name: "--random-seed", description: "Random seed for reproducibility", type: "int", category: "Serving" },
  {
    name: "--sampling-defaults",
    description:
      'Default sampling parameters source: "openai" for OpenAI-compatible defaults or "model" for model defaults.',
    type: "enum",
    defaultValue: "model",
    options: ["openai", "model"],
    category: "Serving",
  },
  {
    name: "--preferred-sampling-params",
    description: "JSON-formatted sampling settings returned by /get_model_info",
    type: "string",
    category: "Serving",
  },
  {
    name: "--grammar-backend",
    description: "Backend for grammar-guided constrained decoding",
    type: "enum",
    options: ["xgrammar", "outlines", "llguidance", "none"],
    category: "Serving",
  },
  {
    name: "--file-storage-path",
    description: "Backend file storage directory path",
    type: "string",
    defaultValue: "sglang_storage",
    category: "Serving",
  },
  {
    name: "--decode-log-interval",
    description: "Log interval (in decode iterations) for decode batch stats",
    type: "int",
    defaultValue: "40",
    category: "Serving",
  },
  {
    name: "--watchdog-timeout",
    description: "Crash the server if a forward batch takes longer than this many seconds",
    type: "float",
    defaultValue: "300",
    category: "Serving",
  },
  {
    name: "--batch-notify-size",
    description: "Number of streaming notifications to batch before yielding to the event loop",
    type: "int",
    defaultValue: "16",
    category: "Serving",
  },
  {
    name: "--stream-response-default-include-usage",
    description: "Include token usage in every streaming response chunk",
    type: "bool",
    category: "Serving",
  },

  // Optimization
  {
    name: "--enable-deterministic-inference",
    description: "Enable deterministic, batch-invariant inference operations",
    type: "bool",
    category: "Optimization",
  },
  {
    name: "--enable-torch-compile",
    description: "Enable torch.compile acceleration. Best for small models at small batch sizes. (Out of maintenance)",
    type: "bool",
    category: "Optimization",
  },
  {
    name: "--enable-p2p-check",
    description: 'Enable P2P access check for multi-GPU. Add if you see "peer access not supported" errors.',
    type: "bool",
    category: "Optimization",
  },
  {
    name: "--enable-fp32-lm-head",
    description: "Use FP32 precision for LM head outputs (logits)",
    type: "bool",
    category: "Optimization",
  },
  {
    name: "--enable-tf32-matmul",
    description: "Use TensorFloat32 for float32 matmuls. CUDA only. Auto-enabled for MiniMax-M2 and GLM-4.",
    type: "bool",
    category: "Optimization",
  },
  {
    name: "--enable-memory-saver",
    description: "Enable memory saver mode to reduce GPU memory usage",
    type: "bool",
    category: "Optimization",
  },
  {
    name: "--disable-log-stats",
    description: "Disable logging of batch statistics",
    type: "bool",
    category: "Optimization",
  },
  {
    name: "--gc-warning-threshold-secs",
    description: "Warn on long garbage collection pauses. Set to 0 to disable.",
    type: "float",
    defaultValue: "0.0",
    category: "Optimization",
  },
  {
    name: "--sleep-on-idle",
    description: "Reduce CPU usage when the server is idle between requests",
    type: "bool",
    category: "Optimization",
  },

  // Speculative decoding
  {
    name: "--speculative-algorithm",
    description: "Speculative decoding algorithm",
    type: "enum",
    options: ["EAGLE", "EAGLE3", "NEXTN", "STANDALONE", "NGRAM"],
    category: "Speculative",
  },
  {
    name: "--speculative-draft-model",
    description: "Draft model path for speculative decoding",
    type: "string",
    category: "Speculative",
  },
  {
    name: "--speculative-draft-model-revision",
    description: "Specific version (branch, tag, or commit) of the draft model",
    type: "string",
    category: "Speculative",
  },
  {
    name: "--speculative-draft-load-format",
    description: "Weight loading format for the draft model",
    type: "string",
    category: "Speculative",
  },
  {
    name: "--speculative-num-steps",
    description: "Number of sampling steps from the draft model per iteration",
    type: "int",
    category: "Speculative",
  },
  {
    name: "--speculative-eagle-topk",
    description: "Number of tokens sampled from the draft model each EAGLE step",
    type: "int",
    category: "Speculative",
  },
  {
    name: "--speculative-num-draft-tokens",
    description: "Number of draft tokens to propose per iteration",
    type: "int",
    category: "Speculative",
  },
  {
    name: "--speculative-accept-threshold-single",
    description: "Accept a single draft token if its probability exceeds this threshold (default 1.0 = disabled)",
    type: "float",
    defaultValue: "1.0",
    category: "Speculative",
  },
  {
    name: "--speculative-accept-threshold-acc",
    description: "Accept threshold applied to accumulated probability. Token accepted if p / threshold >= 1.",
    type: "float",
    defaultValue: "1.0",
    category: "Speculative",
  },
  {
    name: "--speculative-token-map",
    description: "Path to the draft model small-vocab mapping table",
    type: "string",
    category: "Speculative",
  },
  {
    name: "--speculative-attention-mode",
    description: "Attention backend mode for speculative decoding operations",
    type: "enum",
    defaultValue: "prefill",
    options: ["prefill", "decode"],
    category: "Speculative",
  },

  // Advanced (specialized flags: kernel backends, LoRA, disaggregation, update/checkpoint, etc.)
  { name: "--device", description: "Device to use: cuda, xpu, hpu, npu, or cpu", type: "string", category: "Advanced" },
  {
    name: "--base-gpu-id",
    description: "Base GPU ID to start allocating GPUs from",
    type: "int",
    defaultValue: "0",
    category: "Advanced",
  },
  {
    name: "--gpu-id-step",
    description: "Delta between consecutive GPU IDs used for allocation",
    type: "int",
    defaultValue: "1",
    category: "Advanced",
  },
  {
    name: "--fastapi-root-path",
    description: "Path prefix when the app is behind a path-based routing proxy",
    type: "string",
    category: "Advanced",
  },
  { name: "--grpc-mode", description: "Use gRPC server instead of HTTP server", type: "bool", category: "Advanced" },
  {
    name: "--warmups",
    description: "Custom warmup functions (CSV) to run before the server starts accepting requests",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--nccl-port",
    description: "Fixed port for NCCL distributed setup. Random when unset.",
    type: "int",
    category: "Advanced",
  },
  {
    name: "--checkpoint-engine-wait-weights-before-ready",
    description: "Wait for initial weights via checkpoint-engine before serving",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--dist-init-addr",
    description: "Host address for distributed backend initialization (multi-node)",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--nnodes",
    description: "Number of nodes for distributed serving",
    type: "int",
    defaultValue: "1",
    category: "Advanced",
  },
  {
    name: "--node-rank",
    description: "Node rank in a multi-node setup",
    type: "int",
    defaultValue: "0",
    category: "Advanced",
  },
  {
    name: "--load-balance-method",
    description: "Load balancing strategy for data parallelism",
    type: "enum",
    defaultValue: "auto",
    options: ["auto", "round_robin", "follow_bootstrap_room", "total_requests", "total_tokens"],
    category: "Advanced",
  },
  {
    name: "--enable-lora",
    description: "Enable LoRA adapter support for the model",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--enable-lora-overlap-loading",
    description: "Overlap LoRA H2D weight transfers with GPU compute",
    type: "bool",
    category: "Advanced",
  },
  { name: "--max-lora-rank", description: "Maximum LoRA rank to support", type: "int", category: "Advanced" },
  {
    name: "--max-loras-per-batch",
    description: "Max LoRA adapters per running batch",
    type: "int",
    defaultValue: "8",
    category: "Advanced",
  },
  {
    name: "--max-loaded-loras",
    description: "Max LoRA adapters loaded in CPU memory at once",
    type: "int",
    category: "Advanced",
  },
  {
    name: "--lora-eviction-policy",
    description: "LoRA adapter eviction policy when GPU memory is full",
    type: "enum",
    defaultValue: "lru",
    options: ["lru", "fifo"],
    category: "Advanced",
  },
  {
    name: "--lora-backend",
    description: "Kernel backend for multi-LoRA serving",
    type: "enum",
    defaultValue: "csgmv",
    options: ["triton", "csgmv", "torch_native"],
    category: "Advanced",
  },
  {
    name: "--lora-drain-wait-threshold",
    description: "Seconds a LoRA request waits before draining one running adapter",
    type: "float",
    defaultValue: "0.0",
    category: "Advanced",
  },
  {
    name: "--attention-backend",
    description: "Kernel backend for attention layers",
    type: "enum",
    options: ["triton", "torch_native", "flashinfer", "fa3", "fa4", "flashmla", "trtllm_mla", "flex_attention"],
    category: "Advanced",
  },
  {
    name: "--prefill-attention-backend",
    description: "Kernel backend for prefill attention (overrides --attention-backend)",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--decode-attention-backend",
    description: "Kernel backend for decode attention (overrides --attention-backend)",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--sampling-backend",
    description: "Kernel backend for sampling layers",
    type: "enum",
    options: ["flashinfer", "pytorch"],
    category: "Advanced",
  },
  {
    name: "--fp8-gemm-backend",
    description: "Backend for Blockwise FP8 GEMM operations",
    type: "enum",
    defaultValue: "auto",
    options: ["auto", "deep_gemm", "flashinfer_trtllm", "flashinfer_cutlass", "triton", "aiter"],
    category: "Advanced",
  },
  {
    name: "--bf16-gemm-backend",
    description: "Backend for unquantized BF16 GEMM operations",
    type: "enum",
    defaultValue: "auto",
    options: ["auto", "cutedsl", "torch"],
    category: "Advanced",
  },
  {
    name: "--disable-flashinfer-autotune",
    description: "Disable FlashInfer kernel autotuning",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--disagg-mode",
    description: "Disaggregated serving mode: prefill or decode",
    type: "enum",
    options: ["prefill", "decode"],
    category: "Advanced",
  },
  {
    name: "--disagg-tensor-parallel-size-offset",
    description: "TP size offset for the remote side in disaggregated serving",
    type: "int",
    category: "Advanced",
  },
  {
    name: "--update-layer-range",
    description: "Layer range for partial model updates via checkpoint-engine (start-end)",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--update-share-system-runtime-memory",
    description: "Share system memory with runtime for checkpoint-engine updates",
    type: "float",
    defaultValue: "0.8",
    category: "Advanced",
  },
  {
    name: "--enable-streaming-session",
    description: "Enable streaming session mode with StreamingSession wrapper",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--enable-unified-memory",
    description: "Use a single dynamic byte buffer for hybrid Mamba/SWA models instead of static partitioning",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--enable-page-major-kv-layout",
    description: "Use page-granularity KV layout instead of per-layer layout",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--swa-full-tokens-ratio",
    description: "Ratio of SWA layer KV tokens to full layer KV tokens (0-1)",
    type: "float",
    defaultValue: "0.8",
    category: "Advanced",
  },
  {
    name: "--disable-hybrid-swa-memory",
    description: "Disable hybrid SWA memory allocation",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--enable-prefill-delayer",
    description: "Enable prefill delayer for DP attention to reduce idle time",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--prefill-delayer-max-delay-passes",
    description: "Max forward passes to delay prefill",
    type: "int",
    defaultValue: "30",
    category: "Advanced",
  },
  {
    name: "--model-loader-extra-config",
    description: "Extra config JSON passed to the model loader",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--skip-tokenizer-init",
    description: "Skip tokenizer init and pass input_ids directly in generate requests",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--prefill-only-disable-kv-cache",
    description: "Skip physical KV cache for embedding-mode prefill-only workloads",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--model-config-parser",
    description: 'Model config parser: "auto" picks mistral via heuristic, else uses HuggingFace AutoConfig.',
    type: "enum",
    defaultValue: "auto",
    options: ["auto", "hf", "mistral"],
    category: "Advanced",
  },
  {
    name: "--json-model-override-args",
    description: "JSON dictionary to override model config.json values at load time",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--completion-template",
    description: "Builtin completion template name or path to a custom completion template file",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--enable-ssl-refresh",
    description: "Auto-reload SSL certificates when cert/key files change on disk",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--enable-http2",
    description: "Use Granian ASGI server for HTTP/1.1 and HTTP/2 auto-negotiation",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--download-dir",
    description: "Model download directory for HuggingFace models",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--model-checksum",
    description: "Model file integrity verification checksum",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--soft-watchdog-timeout",
    description: "Dump debug info if a forward batch exceeds this timeout (does not crash)",
    type: "float",
    category: "Advanced",
  },
  {
    name: "--dist-timeout",
    description: "Timeout in seconds for torch.distributed initialization",
    type: "int",
    category: "Advanced",
  },
  {
    name: "--load-snapshot-publish-interval",
    description: "Publish load snapshot to shared memory every N decode iterations",
    type: "int",
    defaultValue: "15",
    category: "Advanced",
  },
  {
    name: "--collect-tokens-histogram",
    description: "Collect prompt and generation tokens histograms in metrics",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--enable-metrics-for-all-schedulers",
    description: "Enable Prometheus metrics for all TP ranks, not just TP 0",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--extra-metric-labels",
    description: 'Custom JSON labels for metrics, e.g. \'{"label1": "value1"}\'',
    type: "string",
    category: "Advanced",
  },
  {
    name: "--uvicorn-access-log-exclude-prefixes",
    description: "Path prefixes to exclude from uvicorn access logs",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--abort-on-priority-when-disabled",
    description: "Abort requests that specify a priority when priority scheduling is disabled",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--schedule-low-priority-values-first",
    description: "With priority scheduling, schedule lower integer values first (inverse ordering)",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--priority-scheduling-preemption-threshold",
    description: "Min priority difference for a new request to preempt running ones",
    type: "int",
    defaultValue: "10",
    category: "Advanced",
  },
  {
    name: "--disable-priority-preemption",
    description: "Disable preemption in priority scheduling",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--constrained-json-whitespace-pattern",
    description: "Regex pattern for allowed JSON whitespace in constrained decoding (outlines/llguidance)",
    type: "string",
    category: "Advanced",
  },
  {
    name: "--constrained-json-disable-any-whitespace",
    description: "Enforce compact JSON (no whitespace) in constrained decoding",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--tool-server",
    description: 'Either "demo" or comma-separated list of tool server URLs',
    type: "string",
    category: "Advanced",
  },
  {
    name: "--enable-quant-communications",
    description: "INT8 quantize TP communications. NPU/Qwen3 only.",
    type: "bool",
    category: "Advanced",
  },
  {
    name: "--tool-call-parser",
    description: "Parser for tool-call interactions",
    type: "enum",
    options: [
      "deepseekv3",
      "deepseekv31",
      "glm",
      "glm45",
      "glm47",
      "gpt-oss",
      "kimi_k2",
      "llama3",
      "mistral",
      "pythonic",
      "qwen",
      "qwen25",
      "qwen3_coder",
      "step3",
      "gigachat3",
    ],
    category: "Advanced",
  },
];

export const SGLANG_FLAG_CATEGORIES = [...new Set(SGLANG_FLAGS.map((f) => f.category))];
